name: "base-ci"

on:
  schedule:
    - cron: "0 0 * * *" # 00:00 UTC Everyday
  workflow_dispatch:

jobs:
  base-ci:
    runs-on: ubuntu-latest
    steps:
      - name: "[preparation] checkout"
        uses: actions/checkout@v4.1.1

      - name: "[preparation] set up qemu"
        uses: docker/setup-qemu-action@v3.2.0

      - name: "[preparation] set up docker context for buildx"
        run: docker context create builders

      - name: "[preparation] set up docker buildx"
        uses: docker/setup-buildx-action@v3.6.1
        with:
          endpoint: builders
          driver-opts: image=moby/buildkit:v0.10.6
          platforms: linux/amd64,linux/arm64,linux/arm,linux/ppc64le

      - name: "[preparation] docker login"
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6.7.0
        with:
          context: base/
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm,linux/ppc64le
          sbom: true
          provenance: true

      # - name: "[execution] build the base docker image"
      #   run: |
      #     docker buildx build --output=type=registry --platform linux/amd64,linux/arm64,linux/arm,linux/ppc64le -t portainer/base:latest -f base/Dockerfile .
