name: "base"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # 00:00 UTC Everyday

env:
  DOCKER_HUB_REPO: portainer/base
  IMAGE_TAG: latest

jobs:
  build_images:
    runs-on: ubuntu-latest
    steps:
      - name: "[preparation] checkout"
        uses: actions/checkout@v4.1.1

      - name: "[preparation] set up qemu"
        uses: docker/setup-qemu-action@v3.2.0

      - name: "[preparation] set up docker context for buildx"
        run: docker context create builders

      - name: "[preparation] set up docker buildx"
        uses: docker/setup-buildx-action@v3.6.1
        with:
          endpoint: builders
          driver-opts: image=moby/buildkit:v0.16.0

      - name: "[preparation] docker login"
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: "build and push images"
        uses: docker/build-push-action@v6.7.0
        with:
          context: base/ 
          tags: ${{ env.DOCKER_HUB_REPO }}:${{ env.IMAGE_TAG }}
          platforms: |
            linux/amd64
            linux/arm64
            linux/arm
            linux/ppc64le
          sbom: true
          provenance: true
          push: true
