name: "base-ci"

on:
  schedule:
    - cron: "00 00 * * *" # 00:00 UTC Everyday
  workflow_dispatch:

jobs:
  base-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
      - name: "[preparation] docker login"
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: "[execution] build the base docker image"
        run: |
          docker buildx build --output=type=registry -t portainer/base:latest -f base/Dockerfile .
