name: "base-ci"

on:
  schedule:
    - cron: "0 0 * * *" # 00:00 UTC Everyday
  workflow_dispatch:

jobs:
  base-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: "[preparation] docker login"
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: "[execution] build the base docker image"
        run: |
          docker buildx build --output=type=registry --platform linux/amd64,linux/arm64,linux/arm,linux/ppc64le -t portainer/base:latest -f base/Dockerfile .
