name: Build kubectl docker image to Portainer CI

on:
  push:
    branches:
      - develop
    paths:
      - 'kube-shell/**'
  pull_request:
    branches:
      - develop
    paths:
      - 'kube-shell/**'

env: 
  GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: staging
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: build the image to portainer ci with PR number
        if: ${{ github.event.pull_request.number != '' }}
        run: |
          # make the script executeable 
          chmod +x "${GITHUB_WORKSPACE}/kube-shell/build-and-push.sh"

          # run the script
          "${GITHUB_WORKSPACE}/kube-shell/build-and-push.sh" portainerci pr$GITHUB_PR_NUMBER

      - name: build the image to portainer ci ( Develop Latest )
        run: |
          # make the script executeable 
          chmod +x "${GITHUB_WORKSPACE}/kube-shell/build-and-push.sh"

          # run the script
          "${GITHUB_WORKSPACE}/kube-shell/build-and-push.sh" portainerci latest
