# This is a basic workflow to build amd64/arm64 kubectl image for portainer

name: build

on:
  push:
    branches: develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: build the image
        run: |
          #make the script executeable 
          chmod +x "${GITHUB_WORKSPACE}/kube-shell/build-and-push.sh"

          # run the script
          "${GITHUB_WORKSPACE}/kube-shell/build-and-push.sh"